In [120]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [121]:
set_url="http://academic.udayton.edu/kissock/http/Weather/gsod95-current/INCALCUT.txt"
file_Data = []
import urllib.request

In [122]:
data_set = []
for line in urllib.request.urlopen(set_url):
    temp = line.decode("utf-8").replace("\r\n","")
    temp_list = []
    for elem in temp.split(" "):
        if elem!= '':
            temp_list.append(elem)
    #print(temp_list)
    data_set.append(temp_list)

In [124]:
from sklearn.linear_model  import LinearRegression
from sklearn.model_selection import train_test_split  
from sklearn.metrics import mean_absolute_error, median_absolute_error  

In [126]:
model = LinearRegression() #RNN use, LSTM, TimeSeriesAnalysis

In [127]:
X = []
Y = []
for elem in data_set:
    X.append([int(elem[0]),int(elem[1])])
    Y.append(float(elem[3]))
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=12)

In [128]:
X_train = np.asarray(X_train, dtype=np.int64)
y_train = np.asarray(y_train , dtype=np.int64)

In [129]:
y_train=y_train.reshape(-1,1)

In [130]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [131]:
test = np.array([4,26]).reshape(1,-1)    #[month,day]

In [132]:
prediction = model.predict(X_test)
y_test = np.array(y_test).reshape(-1,1)

In [133]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [134]:
y_test
prediction

array([[69. ],
       [81.3],
       [73.7],
       ...,
       [82.7],
       [75.7],
       [82.8]])

array([[77.69075186],
       [78.59627373],
       [78.63280707],
       ...,
       [78.49201177],
       [78.55112132],
       [78.73706904]])

In [112]:
errormean = mean_absolute_error(y_test, prediction)

In [113]:
errormedian = median_absolute_error(y_test, prediction)

In [135]:
test_res = ((model.predict(test)+errormean)-32)*5/9
errormean
errormedian

7.624858413741629

6.477886618288949

In [136]:
test_res

array([[29.73532631]])

In [137]:
if(test_res>25):
    print("HOTTTT!!!")
elif(test_res<10):
    print("COLD!!!")
else:
    print("It's okay!")

HOTTTT!!!
